title: SalasNorman
description: Learning new things.
url: "https://your-username.github.io"
theme: jekyll-theme-minimal

social:
  linkedin: "https://www.linkedin.com/in/salasnorman/"
  huggingface: "https://huggingface.co/SalasNorman"
